### ISSUE TITLE
Some error in the nexus version

### ISSUE THREAD

**Issue by jendaHolarek** [palinek/pvr.sledovanitv.cz#106]
After the last update, there is some bug in the Kodi Nexus repository (system version 20.2.0) and the addon for Kodi Omega version (21.2.0) is installed instead of the addon version 20.6.0.
![verze kodi](https://github.com/palinek/pvr.sledovanitv.cz/assets/112324326/e3f15132-1f25-40bf-840d-bbaca5e03d99)
![Sledovanitv](https://github.com/palinek/pvr.sledovanitv.cz/assets/112324326/94309fa9-0a13-47dd-9503-b5c671c5fde6)

**Comment by palinek** [comment]
Packaging and uploading to particular repository is not handled by us.
