### ISSUE TITLE
Perental PIN requred

### ISSUE THREAD

**Issue by rkosnar** [palinek/pvr.sledovanitv.cz#107]
It is not possible to play PIN protected channels from sledovani.tv.

##### Expected Behavior
Protected video playback.

##### Current Behavior
It is played video stream with "Parental PIN is required" text.

##### Steps to Reproduce (for bugs)
1. Install kodi
2. Compile and install into Kodi pvr.sledovanitv.cz addon
3. configure addon 
     service = sledovani.tv
     fill login, password etc.
4. open PIN protected channel
5. Enter PIN for opening the channel
  -> Instead of video is played stream  "Parental PIN is required"

##### System Information

* pvr.sledovanitv.cz Version: 20.4, 20.06
* Kodi Version: 20.2
* OS Version: Ubuntu 22.04

**Comment by palinek** [comment]
Fixed in releases 20.7.0-Nexus & 21.3.0-Omega.
