### ISSUE TITLE
OSMC broken with sledovanitv addon

### ISSUE THREAD

**Issue by Krysolet-CZ** [palinek/pvr.sledovanitv.cz#12]
Hello i have a problem with a new version OSMC and sledovanitv addon on my Raspberry PI2. I use clear installation from official website OSMC 2018.08-1 release. After the installation i update on new version Kodi 18. I proceed by the instructions on this website "https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631". When i allow sledovanitv addon, OSMC broken with ugly faces.

Thanks for answers.

**Comment by palinek** [comment]
What version of the kodi build are you using? Arr you using inputstream.adaptive? Based on the latest osmc forum posts, there are problems with the latest input stream adaptive.

Also to further track the problem...can you save/dump the kodi logs as described in the osmc tutorials?

**Comment by Krysolet-CZ** [comment]
I use this version Kodi:
08:19:07.119 T:1917566976  NOTICE: Starting Kodi (18.0-BETA5). Platform: Linux ARM (Thumb) 32-bit
08:19:07.119 T:1917566976  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
08:19:07.119 T:1917566976  NOTICE: Kodi compiled Oct 25 2018 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.30 (264478)

I don't use inputstream.adaptive.

And here is my logfile: https://paste.osmc.tv/aposixuzad

**Comment by palinek** [comment]
`rbp2-mediacenter-osmc                17.8-347` 

There are many reports in the osmc forum, that the verions 346 and 347 are broken/have issues/. Plese, try to downgrade to 345,  it can make things better.

**Comment by Krysolet-CZ** [comment]
Thank you i try it. I solved this problem with installation OpenELEC instead of OSMC. It works fine. 

Best regards Michal
