### ISSUE TITLE
Archive support

### ISSUE THREAD

**Issue by KOPRajs** [palinek/pvr.sledovanitv.cz#13]
Hi,
there is currently an ongoing effort to bring archive support to Simple IPTV PVR client, see here:
https://discourse.coreelec.org/t/coreelec-with-iptv-archive-support/1950

The code is here:
https://github.com/CoreELEC/CoreELEC/blob/master/packages/mediacenter/kodi-binary-addons/pvr.iptvarchive/patches/iptvarchive-0001-add-archive-support.patch

Possibly this could be partialy reused to add the archive support for sledovanitv.cz as well.

**Comment by palinek** [comment]
What do you miss in here? You can play past EPG events right now (if you have such service paid/available).

**Comment by KOPRajs** [comment]
Sorry, I was told it was not possible and I haven't checked that myself. It works indeed, my bad. Might be useful to update the addon description.
