### ISSUE TITLE
Náhodná funkčnost/nefunkčnost

### ISSUE THREAD

**Issue by rdolezel** [palinek/pvr.sledovanitv.cz#18]
Ahoj,
mohl bych poprosit o radu, co zkontrolovat, abych zjistil, proč plugin někdy funguje a někdy po označení pořadu jen problikne obrazovka a jsem zpět na EPG?

Včera jsem upgradnul Kodi na final 18 jak na W10 notebooku, tak na Minix Neo U1 (ARM S905), následně upgradnul plugin sledovanitv.cz na nabízenou verzi. Po půlnoci jsem ještě kontroloval funkčnost, označil jeden pořad v minulosti jako nahrávku, vše šlapalo. Dnes ráno si nepustím nic, ani live, ani nahrávku, natož "odcouvání" do minulosti, jak na Minixu, tak na notebooku s W10.

Zkoušel jsem vypnout/zapnout HEVC, přepnout SD/HD, všechny kombinace, ale nic. Proto si myslím, že problém bude někde dál, ale nevím, jak to zdetekovat.

Díky.

**Comment by palinek** [comment]
Please, enable debug logging and check kodi's log for problems/errors/warnings...

**Comment by triksmelb** [comment]
Hello,
I have 2 PVR Add-on clients for different countries. 
Is there a way to off-set the EPG / Channel data for sledovanitv add-on only?
I'd be happy to adjust it in the code if that is the only way...
thanks

**Comment by rdolezel** [comment]
@palinek: Thanks for your answer. I reviewed the log and found surprising message "Unable to resolve sledovanitv.cz". Although EPG was successfully read for all channels it seems another DNS resolution is initiated when any tv show or recording is chosen to be played. One of my DNS servers didn't work properly or didn't respond fast enough. Everything is ok after I removed this DNS server from IP configuration on my Kodi devices.

**Comment by palinek** [comment]
@rdolezel thanks for info

**Comment by palinek** [comment]
> Is there a way to off-set the EPG / Channel data for sledovanitv add-on only?
I'd be happy to adjust it in the code if that is the only way...

@triksmelb fair request... but has nothing to do with this issue.
