### ISSUE TITLE
Spatna prace s casovou zonou

### ISSUE THREAD

**Issue by Kozzi11** [palinek/pvr.sledovanitv.cz#21]
Zkousel jsem v kodi pouzivat tento doplnek a musim rict super prace. Jedine co je trochu neprijemne ze se zda ze doplnek spravne nezpracovava casovou zonu. Vsechny informace o programech jsou o hodinu posunuty vuci realu

**Comment by palinek** [comment]
Please, be more verbose. You didn't provide any relevant information -> os/sw version information, the exact problem description ("Vsechny informace o programech jsou o hodinu posunuty vuci realu" is too vague and I can't do much with it).

**Comment by Kozzi11** [comment]
Ok, sorry for not so very descriptive text :). I am using your plugin on Techbite Flix TVBOX (AndroidTV 8 Oreo).

Kodi version: 18.0
pvr.sledovani.tv version: 1.4.7

Here is a screenshot of tv guide:
https://photos.app.goo.gl/yZsakkjmZZjK2i1K7

As you can see for eg. Top Gear 2008 seems to be at 9:55 to 11:05 but it should be 10:55 to 12:05

So it seems that your plugin use GMT instead of GMT+1 as a timezone

Thank you for your response.

If you need anything else just ask and I will try to add as much info as I could

**Comment by palinek** [comment]
What local timezone is set on your box? (in kodi Settings -> Interface -> Regional -> Timezone country)

**Comment by Kozzi11** [comment]
Ok it seems there is no such an option for kodi on android: https://forum.kodi.tv/showthread.php?tid=331166

So I checked my androidTV settings and it seems there is everything ok: https://photos.app.goo.gl/YVZcFkaA9vamWfBg7

**Comment by palinek** [comment]
Just tried on an android phone...changed the timezone and I saw no changes in the presented program guide. Strange.

Note: pvr.sledovanitv.cz (or any other pvr addon) gives the start/end times to kodi in seconds since epoch... so changing local time zone of system should make a difference in the program guide

**Comment by palinek** [comment]
There's a funny typo in the code, that I've just discovered. Can you have a look into #22?
