### ISSUE TITLE
Add support for PVR_RECORDING.iChannelUid

### ISSUE THREAD

**Issue by ksooo** [palinek/pvr.sledovanitv.cz#23]
Please add support for PVR_RECORDING.iChannelUid. Although PVR Addon API declares this property as optional, some Kodi features cannot work if the channel uid is not given with a recording, namely the "red dot" indicating an in-progress recording in pvr recordings window and recently recorded home screen widget, the right context menu entries for recordings in progess, maybe others.

Unfortunately, there is no reliable fix in Kodi possible without an PVR addon API change (which I plan for Kodi v19, btw.).

Thus, I kindly ask the maintainer of this addon or anybody else with the needed skills to add support for PVR_RECORDING.iChannelUid so we can fix the above mentioned issues for Kodi v18.

Thanks.

**Comment by palinek** [comment]
I'll have a look on this... thanks for reporting.

**Comment by ksooo** [comment]
Thanks, btw. and unrelated to this issue: support `PVR-RECORDING.channelType` (https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_types.h#L549) would be also an improvement. Kodi cannot determine this by itself and defaults to TV if not given by the addon (see respective warning in kodi.log).

**Comment by palinek** [comment]
> support PVR_RECORDING.channelType

This is already set by this addon -> https://github.com/palinek/pvr.sledovanitv.cz/blob/master/src/PVRIptvData.cpp#L1032

**Comment by ksooo** [comment]
> This is already set by this addon

 Nice. I must have overlooked this in the first place, sorry.

**Comment by palinek** [comment]
Done in dbb88250e3220cf44f9cd54691c505d5a14c822c

**Comment by ksooo** [comment]
Cool, thanks.
