### ISSUE TITLE
Timeshift probíhajícího programu

### ISSUE THREAD

**Issue by MiloshCZ** [palinek/pvr.sledovanitv.cz#24]
Ahoj,
šlo by nějak udělat, aby bylo možné spustit právě probíhající program od začátku? Ukončený spustit lze, je možné v něm i přetáčet (dopředu, dozadu), ale jestliže aktuální program ještě běží, tak není možné se vrátit zpět a koukat "ze záznamu".
Nevím jestli to není způsobeno balíčkem "NP+", jestli se to nechová jinak než s "Zpětné přehrávání až 7 dní + Nahrávky 50 hodin + NP+"
Spouštím to z EPG volbou "přehrát program".
![image](https://user-images.githubusercontent.com/13035760/52945733-b48df000-3372-11e9-9031-3e30b72bcd61.png)
Probíhající program:
![image](https://user-images.githubusercontent.com/13035760/52945807-de471700-3372-11e9-8878-b70d145000fb.png)
Ukončený program:
![image](https://user-images.githubusercontent.com/13035760/52945867-059de400-3373-11e9-93c2-238962895ee2.png)
Edit: testuju to na Win32 buildu. Používám Kodi na windowsech. Jako oplátku můžu poskytnout Win32 buildy

**Comment by palinek** [comment]
Please, use the issue template. It really helps in solving issues...

**Comment by palinek** [comment]
With the `inputstream.adaptive` addon installed and used by `pvr.sledovanitv.cz` the timeshift functionality works as expected.
