### ISSUE TITLE
Feature request: PIN kód

### ISSUE THREAD

**Issue by MiloshCZ** [palinek/pvr.sledovanitv.cz#25]
Ahoj,
měl bych prosbu. Bylo by možné přidat podporu pro PIN kód? Klidně do konfigurace pro trvalé zapnutí/vypnutí chráněných kanálů.

**Comment by Vasek79** [comment]
Přidávám nějaké info k rodičovskému zámku. Původně jsem to psal k P. Rokosovi.

"Zamknutí" je na serverové straně. z klienta se musí odeslat PIN, který se nastaví v nastavení účtu na stránkách sledovanitv.cz
![obrazek](https://user-images.githubusercontent.com/31768006/52948841-e60ab980-337a-11e9-9d15-160dfe9fb7b6.png)

_Originally posted by @Vasek79 in https://github.com/PepaRokos/pvr.sledovanitv/issues/15#issuecomment-464701328_

**Comment by Vasek79** [comment]
Přidávám debug log z Kodi.
 
[leo_debug_log_locked.log](https://github.com/PepaRokos/pvr.sledovanitv/files/2923009/leo_debug_log_locked.log)

Je tam vidět, že přehrávači je při zamknutém rodičovském zámku předhozen soubor pin.ts - video s textem o odemknutí rodičovského zámku.

Ve webovém prohlížeči to při NEODEMKNUTÉM ZÁMKU vypadá nějak takhle:
![playback pinunlock](https://user-images.githubusercontent.com/31768006/53694247-5dddd880-3dac-11e9-8189-325007325f8e.png)


při ODEMKNUTÉM ZÁMKU je to takhe:

![playback playlive](https://user-images.githubusercontent.com/31768006/53694252-6cc48b00-3dac-11e9-8804-e53f70b20b80.png)

**Comment by DanielKrasny** [comment]
API volání pro odemknutí 18+ kanálů je:
```
https://sledovanitv.cz/api/pin-unlock?pin=0000&PHPSESSID=
```

Pokud si pamatuji, výstupem je totéž, co z volání `playlist`, ale pouze v případě, že máte ve své nabídce právě 18+ kanály.

Bohužel, sám takový balíček nemám a nemohu tedy otestovat, ani implementovat tuto možnost do PVR.

**Comment by Vasek79** [comment]
Tak SledovaniTV zase dali do nabídky 18+ kanály, tak jsem to zkusil a bohužel odemknutí kanálů nefunguje.Neukáže se nic, kam by bylo možné zadat pin.

**Comment by MiloshCZ** [comment]
Našel jsem "workaround". Existuje plugin "Archiv SledovaniTV" https://www.xbmc-kodi.cz/prispevek-archiv-sledovanitv

**Comment by palinek** [comment]
Please, test #40 (note: installable packages can be found here https://jenkins.kodi.tv/blue/organizations/jenkins/palinek%2Fpvr.sledovanitv.cz/detail/pin_unlock/2/artifacts)

**Comment by MiloshCZ** [comment]
Builds are for Matrix or Leila version of Kodi?

**Comment by palinek** [comment]
> Builds are for Matrix or Leila version of Kodi?

The PR aims to Matrix.

**Comment by karel-un** [comment]
> > Builds are for Matrix or Leila version of Kodi?
> 
> The PR aims to Matrix.

@palinek would you be so kind and backport this commit to Leia? Thanks.

**Comment by palinek** [comment]
> would you be so kind and backport this commit to Leia? Thanks.

Here -> https://github.com/palinek/pvr.sledovanitv.cz/commit/c54fe018317d62c3da3c42a9a69b0d353fec8c81 , but note that I only applied the patch and tried if it compiles... no testing at all. (sorry, but I'm lacking free time to support multiple versions)

**Comment by MiloshCZ** [comment]
Tested on Kodi 32 bit. PIN ulock is OK, but there is wrong EPG info for locked channels.
![image](https://user-images.githubusercontent.com/13035760/70308931-9fecec80-180c-11ea-812b-b8210a0617e0.png)
![image](https://user-images.githubusercontent.com/13035760/70308941-a7ac9100-180c-11ea-8ac7-5a8f5da8f1f3.png)
![image](https://user-images.githubusercontent.com/13035760/70309009-d3c81200-180c-11ea-8663-a7d4b7cd5473.png)

**Comment by karel-un** [comment]
> > would you be so kind and backport this commit to Leia? Thanks.
> 
> Here -> [c54fe01](https://github.com/palinek/pvr.sledovanitv.cz/commit/c54fe018317d62c3da3c42a9a69b0d353fec8c81) , but note that I only applied the patch and tried if it compiles... no testing at all. (sorry, but I'm lacking free time to support multiple versions)

I can confirm that PIN unlocking backported to v1.6.0 works on Kodi Leia 18.4, Raspberry 4, Raspbian Buster. ~~EPG info is ok, I have not observed problems with EPG info as @MiloshCZ did.~~

EDIT: After some time there are few occurrences where EPG info of one channel is copied to another channel. Not for whole channel, just for one program item. Reboot doesnt help but changes error items.

Thanks @palinek !

**Comment by jiripaskov** [comment]
Please could you tell me how to install this modified addon into Kodi (coreelec - linux)? In the zip file is the addon itself or I must to create it somehow? Thank you.

**Comment by karel-un** [comment]
> Please could you tell me how to install this modified addon into Kodi (coreelec - linux)? In the zip file is the addon itself or I must to create it somehow? Thank you.

Follow build instructions for branch Leia, but in step 2. replace
```
git clone --branch Leia https://github.com/palinek/pvr.sledovanitv.cz.git
```
with
```
git clone --branch Leia_pin https://github.com/palinek/pvr.sledovanitv.cz.git
```
