### ISSUE TITLE
Unable to change language on multi-language channels

### ISSUE THREAD

**Issue by triksmelb** [palinek/pvr.sledovanitv.cz#27]
Some channels contain multiple audio streams with different languages.

Viewer should be able to select the desires audio stream in Kodi during playback or from Kodi default language settings.

Currently there is one audio stream only which is incorrectly labeled not representing the actual language of the audio stream.

Perhaps extracting each audio stream could be possible...

![image](https://user-images.githubusercontent.com/12489962/54864182-910df900-4da7-11e9-8af6-a7311b2df251.jpg)

**Comment by palinek** [comment]
Playback of audio/video streams is completely under control of Kodi (the default stream backend or inputstream.adaptive addon). pvr.sledovanitv.cz just provides stream URL.
