### ISSUE TITLE
TV program limited to one day back degrades Timeshift usage

### ISSUE THREAD

**Issue by ExSport** [palinek/pvr.sledovanitv.cz#33]
As the TV program is limited to one day back only, it is not possible to play recent movies via browsing TV program as you can't go back in time more than 24 hours.
When I changed time in OS and forced to read EPG data for the program, I was able to see programs older than 24hrs only and was able to play it (if it passed already) or record it via creating a timer (if it didn't start). When fixing OS time back, in a while movie is populated in the recorded list and can be played.
Is it possible to browse tv program back in time more than 24hrs to be able use timeshifting? Right now when e.g. you are trying to play anything from Saturday 23:00 at Monday 00:05, it is not possible.
Thanks for your work and great plugin!

##### System Information
* pvr.sledovani.tv Version: 1.5.0
* Kodi Version: 18.2 - 19.x
* OS Version: Android 5.1.1 - 9.0

**Comment by palinek** [comment]
> As the TV program is limited to one day back only

No, it is not. The EGP time span is driven by Kodi (Settings -> PVR & Live TV -> Guide -> Past days to display | Future days to display).

**Comment by ExSport** [comment]
@palinek 
Thank you!
Tried to find it in the settings but probably forgot to check it not only in plugin but Kodi too.
Sorry for invalid issue 😊

**Comment by palinek** [comment]
> Sorry for invalid issue

No problem.
