### ISSUE TITLE
Compilation fails for leia branch

### ISSUE THREAD

**Issue by TomasWallflower** [palinek/pvr.sledovanitv.cz#39]
##### Current Behavior
Problem during compilation of leia branch for kodi 18.4 on Raspberry Pi 3. Also affects plugin in official debian repository (contains only files for /usr/share/doc, not the addon itself)
```
/home/pi/pvr.sledovanitv.cz/src/client.cpp:295:11: error: conflicting declaration of C function ‘PVR_ERROR GetEPGForChannel(ADDON_HANDLE, int, time_t, time_t)’
 PVR_ERROR GetEPGForChannel(ADDON_HANDLE handle, int iChannelUid, time_t iStart, time_t iEnd)
```
##### System Information
* pvr.sledovani.tv Version: leia 
* Kodi Version: 18.4
* OS Version: Raspbian Buster

**Comment by palinek** [comment]
I've just tried to build locally and everything succeeded. The last jenkins' build was also successful -> https://jenkins.kodi.tv/blue/organizations/jenkins/palinek%2Fpvr.sledovanitv.cz/detail/1.5.1-Leia/3/pipeline

Please, be more specific ....

Also note that there is no `GetEPGForChannel` definition/prototype on [line 295 in client.cpp](https://github.com/palinek/pvr.sledovanitv.cz/blob/Leia/src/client.cpp#L295)

**Comment by TomasWallflower** [comment]
There IS GetEPGForChannel on line 295 (https://github.com/palinek/pvr.sledovanitv.cz/blob/19e8297cceee70e488e5335d850457bf47187778/src/client.cpp#L295)
and if I comment it out, compilation is successful, plugin can be installed, but when trying to enable it in Kodi, it fails with unknown error.

**Comment by TomasWallflower** [comment]
If i install package kodi-pvr-sledovanitv-cz from raspbian buster repository, the package contains only those files:
```
pi@raspberry: sudo dpkg -L kodi-pvr-sledovanitv-cz
/.                                                                                                                                                                                    /usr
/usr/share
/usr/share/doc
/usr/share/doc/kodi-pvr-sledovanitv-cz
/usr/share/doc/kodi-pvr-sledovanitv-cz/changelog.Debian.gz
/usr/share/doc/kodi-pvr-sledovanitv-cz/copyright
```

**Comment by palinek** [comment]
> There IS GetEPGForChannel on line 295 (

No, it is not, as I told and gave a link before. What you're linking/pasting here is on `Matrix` branch.

**Comment by TomasWallflower** [comment]
I see that know, I copied build instructions from readme and missed that there is no ```--branch leia``` in git clone pvr-sledovanitv command. 
So I recommending to fix this for other dumbs like me.

**Comment by palinek** [comment]
> I see that know, I copied build instructions from readme and missed that there is no `--branch leia` in git clone pvr-sledovanitv command.

Updated 3328a69
