### ISSUE TITLE
Channel order problem

### ISSUE THREAD

**Issue by jiripaskov** [palinek/pvr.sledovanitv.cz#41]
Hello. Running coreelec with Leia. Sledovanitv 1.5.1.1. 
If I set PVR and LIVE STREAM in KODI to not allow channel order from PVR and create my own channel order inside KODI > it is mixed everytime I restart. Not sure if problem is in KODI itself or it has something to do with addon. Could you point me where to start? Thanks.

**Comment by palinek** [comment]
Hi, sorry to be late, but I somehow forgot about this question. This pvr addon does not do anything concerning sorting. Please, try to ask in kodi irc/forum/support...
But if something is needed on our side, please, let us then know..
