### ISSUE TITLE
Howto install on ubuntu bionic

### ISSUE THREAD

**Issue by zbynekwinkler** [palinek/pvr.sledovanitv.cz#42]
I am on ubuntu bionic. I've added the team-xbmc/ppa respository and installed kodi 18 and kodi-pvr-sledovanitv-cz_1.5.1-1~bionic_amd64.deb. However, no pvr plugin appeared in kodi. Further investigation lead me to unpack the package and it actually does not contain anything except some doc files.

<pre><font color="#729FCF"><b>/tmp</b></font>$ dpkg-deb -R /var/cache/apt/archives/kodi-pvr-sledovanitv-cz_1.5.1-1~bionic_amd64.deb sledovanitv/
<font color="#729FCF"><b>/tmp</b></font>$ cd sledovanitv/
<font color="#729FCF"><b>/tmp/sledovanitv</b></font>$ tree
<font color="#729FCF"><b>.</b></font>
├── <font color="#729FCF"><b>DEBIAN</b></font>
│   ├── control
│   └── md5sums
└── <font color="#729FCF"><b>usr</b></font>
    └── <font color="#729FCF"><b>share</b></font>
        └── <font color="#729FCF"><b>doc</b></font>
            └── <font color="#729FCF"><b>kodi-pvr-sledovanitv-cz</b></font>
                ├── <font color="#EF2929"><b>changelog.Debian.gz</b></font>
                └── copyright

5 directories, 4 files
</pre>

Is this the supported way to get this plugin working on ubuntu bionic? I am using my notebook to evaluate kodi with this plugin as our new home media computer, while the final platform is most likely to be RPi4 with LibreELEC.

**Comment by palinek** [comment]
Please, report this to your PPA maintainers as it is definitely a downstream issue.
For RPi you could have a look into OSMC.
