### ISSUE TITLE
Vicenasobne sparovani zarizeni

### ISSUE THREAD

**Issue by PeS-hkfree** [palinek/pvr.sledovanitv.cz#44]
zdravim,
pouzivam plugin 1.5.1.1 na libreleec leia a kdyz jsem se podival na nastaveni stranek https://sledovanitv.cz/account/devices, je tam videt vicenasobne parovani. Je mozne to upravit tak, aby to bylo sparovane pouze jednou?
Nebo to po provedenych zmenach neni mozne a znamena to definitvni konec sledovanitv na kodi zarizenich?

**Comment by palinek** [comment]
Today I realized a scenario where there was new pairing created when previous login failed. The fix is already released (versions 2.4.2 & 1.6.2).
