### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Krysolet-CZ** [palinek/pvr.sledovanitv.cz#46]
Hello,
after last update addon has stopped working on all of devices...:-(

**Comment by palinek** [comment]
Please, fill out the issue template with the relevant information. I'm not a magician...

**Comment by Krysolet-CZ** [comment]
For example:
Device:

Windows 10,
Kodi 18.6
Addon from official repository 1.6.2.

Same problem is on the raspberry device with Kodi 18.4. and official repository too.

**Comment by palinek** [comment]
I still can't do anything for you w/o logs.

**Comment by Krysolet-CZ** [comment]
Here is log file...
[kodi.log](https://github.com/palinek/pvr.sledovanitv.cz/files/4343501/kodi.log)

**Comment by palinek** [comment]
> Here is log file...
kodi.log

```
2020-03-17 13:46:12.209 T:11016   ERROR: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Error indicated in response. status: 0, error: pairing limit reached
```
Check your devices list on web page and remove unneeded ones.

**Comment by palinek** [comment]
... and remove the log from here as in the debug messages there is your password also.

**Comment by Krysolet-CZ** [comment]
My devices list is free and was free before create a log file...
![Výstřižek](https://user-images.githubusercontent.com/44582497/76859921-735c5e00-685a-11ea-84e4-0d4ab23288fa.PNG)
