### ISSUE TITLE
Cannot pair device

### ISSUE THREAD

**Issue by drbohlav** [palinek/pvr.sledovanitv.cz#47]
Hi,
I compiled a new version of the addon yesterday but can't load the channel list. There are messages like:
- Error indicated in response. status: 0, error: pairing limit reached
- Error in pairing response.
- Cannot pair device
Kodi 18.5 @ Raspbian Buster, pvr.sledovanitv.cz-1.6.2
Thanks a lot for any fix.

**Comment by palinek** [comment]
There is nothing we can do on addon side. Seldovani's server denies the pairing. Check your devices list on their's webpage and/or try also the official app on a phone.

**Comment by drbohlav** [comment]
Thanks for the reply.
I checked the devices on the server, in case of web player or VLC I see new devices. In case of pvr.sledovanitv.cz addon, no new devices will appear and the addon will not load anything from the server. If nothing can be modified on addon side, does it mean that its functionality is over?
Thank you.

**Comment by palinek** [comment]
If you are able to pair with smartphone (official app), then you should be able to pair with kodi's pvr.sledovanitv.cz, I believe.

**Comment by drbohlav** [comment]
Mobile app login also didn't work.
There was a problem with the device limit for my account, which may have been caused by previous versions of your plugin. Although I deleted all the devices in my profile.
I asked sledovani.tv to reset this limit and now the playback is working. Perhaps the problem will not repeat. Thank you.

**Comment by palinek** [comment]
Glad to hear, you've sorted this out.
