### ISSUE TITLE
PVR artwork feature implementation

### ISSUE THREAD

**Issue by cdps82** [palinek/pvr.sledovanitv.cz#50]
Hi Palinek,

first of all thank you very much for all you're doing.. Much appreciated, man. 

I was wondering if you could implement the PVR artwork feature. Basically it's the idea coming from the last and official sledovanitv.cz AndroidTV box (and app). It downloads the Live TV show pictures directly from the official sledovanitv.cz server accordingly to the ID of the show. 

Here is the example of the download ticket that is played right now: 
ht*ps://sledovanitv.cz/epg/event-new?eventId=ct1%3A2020-03-26-126032230&showActions=1, 

ht*ps://sledovanitv.cz/static/posters/682/1031682_150.jpg.

Many thanks,
Petr

**Comment by palinek** [comment]
Yes, nice feature. But this would mean to trigger `api/event-timeshift?eventId=...` for each EPG event and IMO produce a reasonably higher load to servers. So I'm not sure about it...

**Comment by johny-mnemonic** [comment]
In case the official app is doing that as well, servers should be ready for it.
You can even ask support, what they think about that, but I see it unnecessary...

**Comment by palinek** [comment]
> In case the official app is doing that as well, servers should be ready for it.

Yes, but the native app can fetch the information only when it is needed (user is watching on the EPG details). But in our addon we don't have such information and need to provide to kodi the `poster` URL for each EPG event loaded..

**Comment by johny-mnemonic** [comment]
That looks very similar to me then.
You would provide poster URL and when user opens the details of the event, Kodi downloads the poster image. 
I was previously a bit afraid, you have to download all those images, when compiling EPG, but if you just provide URL, it should be fine.

**Comment by palinek** [comment]
> You would provide poster URL and when user opens the details of the event, Kodi downloads the poster image.

But as I've said previously... the poster URL is not known in time of getting EPG information.

> I was previously a bit afraid, you have to download all those images, when compiling EPG, but if you just provide URL, it should be fine.

And you were afraid with a reason. We don't have the poster URL in response of getting EPG list. And to get it we would need to query `api/event-timeshift` for each one of the EPG events.... meaning tons of requests to backend while loading/refreshing EPG list.

**Comment by palinek** [comment]
Hi,
 today I tried to implement this (of course with getting the event info & poster URL triggered only if needed). I succeeded with it, but the problem here is that `/api/event-timeshift` is returning information only for past events (available for the user as timeshift). Till now I'm not aware of any JSON API equivalent to web's `/epg/event-new`. So for future events currently I'm stuck ....

**Comment by palinek** [comment]
Implemented in 6619617
