### ISSUE TITLE
Na Ubuntu v KODI 18.6 addon nie je k dispozícii

### ISSUE THREAD

**Issue by pa4k** [palinek/pvr.sledovanitv.cz#52]
ani po nainštalovaní cez terminál sa mi tento PVR addon nezobrazuje v doplnkoch na inštalácii KODI 18.6 ktorú mam na Ubuntu. Skúšal som addon remove-nuť a znova nainštalovať, inštalácia zbehne korektne ale v KODI tento addon stále nie je ani k povoleniu iné PVR addony mam naištalované a tie funguj napr. simple client viď. screen dole.

##### System Information

* pvr.sledovani.tv Version:  posledná verzia s oficialneho kodi repo
* Kodi Version: 18.6
* OS Version: Ubuntu 19.10

##### Kodi's Log

![pvr-sledovaniTV-cz](https://user-images.githubusercontent.com/49378254/77861578-0c558680-7216-11ea-9f5f-933a67504af1.png)

**Comment by palinek** [comment]
Donwnstream issue. Please, contact/report in your distro bug tracker.

**Comment by Jokertwo** [comment]
> ani po nainštalovaní cez terminál sa mi tento PVR addon nezobrazuje v doplnkoch na inštalácii KODI 18.6 ktorú mam na Ubuntu. Skúšal som addon remove-nuť a znova nainštalovať, inštalácia zbehne korektne ale v KODI tento addon stále nie je ani k povoleniu iné PVR addony mam naištalované a tie funguj napr. simple client viď. screen dole.
> 
> ##### System Information
> * pvr.sledovani.tv Version:  posledná verzia s oficialneho kodi repo
> * Kodi Version: 18.6
> * OS Version: Ubuntu 19.10
> 
> ##### Kodi's Log
> ![pvr-sledovaniTV-cz](https://user-images.githubusercontent.com/49378254/77861578-0c558680-7216-11ea-9f5f-933a67504af1.png)

Hi,
I would like to ask you how did you solved this issue?

**Comment by pa4k** [comment]
Hi, not at all. I don't use it on ubuntu. On win it works fine.

-------- Pôvodná správa --------Od: Petr Laštovka 
Predmet: Re: [palinek/pvr.sledovanitv.cz] Na Ubuntu v KODI 18.6 addon nie je k dispozícii (#52) 



ani po nainštalovaní cez terminál sa mi tento PVR addon nezobrazuje v doplnkoch na inštalácii KODI 18.6 ktorú mam na Ubuntu. Skúšal som addon remove-nuť a znova nainštalovať, inštalácia zbehne korektne ale v KODI tento addon stále nie je ani k povoleniu iné PVR addony mam naištalované a tie funguj napr. simple client viď. screen dole.

System Information



pvr.sledovani.tv Version:  posledná verzia s oficialneho kodi repo

Kodi Version: 18.6

OS Version: Ubuntu 19.10



Kodi's Log





Hi,

I would like to ask you how did you solved this issue?

**Comment by Jokertwo** [comment]
Hi, in the end, I found a solution on how to use it on Raspberian (on Ubuntu it will be the same). It will work only for **Kodi Leia**!.  I have to follow these steps:

1. Clone this repository [(palinek / pvr.sledovanitv.cz)](https://github.com/palinek/pvr.sledovanitv.cz) and switch to branch Leia 
   `git checkout -b leia origin/Leia`
2. Clone [xbmc](https://github.com/xbmc/xbmc) and switch to branch Leia 
   `git checkout -b leia origin/Leia`
3. Build this project (cmake... -> make -> make package-addons) as is it described in the readme
4. In Kodi select possibility _Install from ZIP_ and use zip created by the build
