### ISSUE TITLE
Locked channels - parental lock

### ISSUE THREAD

**Issue by dmnc-net** [palinek/pvr.sledovanitv.cz#54]
Hi,
in the SledovaniTV's [profile](https://sledovanitv.cz/account/profile) one can set parental lock (PIN) to lock/unlock some channels (primary adult content). I'm testing this addon and it seems there is no unlocking support. Right?

**Comment by dmnc-net** [comment]
I'm sorry ... I found out I'm using this addon [PepaRokos/pvr.sledovanitv](https://github.com/PepaRokos/pvr.sledovanitv)

**Comment by johny-mnemonic** [comment]
@dmnc-net then you are using the wrong one, as that one is unmaintained for quite some time.
Switch to this one. I think there already was feature request for PIN here, but not sure, whether it was already fulfilled...
