### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by Harvie** [palinek/pvr.sledovanitv.cz#57]
Readme says:
`git clone --branch master https://github.com/xbmc/xbmc.git`

But i've added `--depth=1` to the git command which resulted in command being finished WAAAY faster while using way less diskspace... Which is especially usefull when compiling on SDcard of raspberry pi... Maybe it would be nice to mention in readme...

**Comment by palinek** [comment]
In most recent README there is the example with --depth switch also.
