### ISSUE TITLE
H.265 mode not working

### ISSUE THREAD

**Issue by Harvie** [palinek/pvr.sledovanitv.cz#61]
Hi. I am using leia on raspberry pi 4B and H.265 (HEVC) mode is not working... Is that supposed to work or is that experimental yet?

**Comment by palinek** [comment]
No. It is not experimental.

**Comment by Harvie** [comment]
So is there something that i could have misconfigured or missing? When i enable H.265 i only have black screen when i start the playback...

**Comment by palinek** [comment]
I really don't know. You didn't provide any relevant information. See your logs for further investigation.

**Comment by Harvie** [comment]
Ok. Thanks. I just wanted to confirm it is actually supposed to work on raspi 4B... I will gather the logs as soon as i will be in presence of the affected device.

**Comment by Harvie** [comment]
So i've noticed following in dmesg:

```
[  697.551335] [vc_sm_ioctl_alloc]: failed to allocate memory on videocore (status: 0, trans_id: 2547)
[  697.551343] [vc_sm_ioctl_alloc]: failed to allocate "Video Frame" data (-12) - type 1, base 67108864 (67108864), num 1, alignment 4096
[  702.305701] vchiq: 0: ignoring ERROR from callback to service 52008
```
It even caused kodi to crash.

I've put `gpu_mem=512` line to `/boot/config.txt`, rebooted and this issue was resolved. I guess the default video memory value of 64MB was just not enough for the decoder. Perhaps you may mention this in readme or somewhere in the configuration tooltip?

I still have some issues with video playback getting stuck every now and then (both h.264 and h.265), but i will have to debug this further... I've tried to increase kodi buffer/memorysize in `advancedsettings.xml`, but it didn't helped. I also checked RAM, CPU and IO usage, which are usualy under 25%. Internet connection speed shows stable 30Mbps, which should be enough as well... But it still happens to me that 2 to 4 times a hour, the TV playback just freezes for like 20 seconds or so and continues after a while... I use inputstream adaptive.

Do you have any tips what should i look for? I will try to get some more logs...

**Comment by palinek** [comment]
This all seems to be specific to your environment (pi4/OS/kodi/configuration...).
