### ISSUE TITLE
playback from past for actual show

### ISSUE THREAD

**Issue by lukyrys** [palinek/pvr.sledovanitv.cz#71]
it there any solution for previous playback actual show?
is possible to play back only the program that has already ended but is not possible to start a show that is still running from the beginning or only pause actual playback

**Comment by mirousek** [comment]
@lukyrys Install Adaptive Inpustream plugin into Kodi (https://kodi.wiki/view/Add-on:InputStream_Adaptive). After that it should begin to work :)

**Comment by johny-mnemonic** [comment]
@mirousek I can confirm, that it is possible to pause playback with that plugin (which is great improvement), but anything else is either flaky (i.e. forwarding to skip ads) or doesn't work at all (i.e. rewinding to the start of the show).

**Comment by mirousek** [comment]
@johny-mnemonic Strange. I thought pause worked even without the plugin.

Try to go to `Settings` -> `Add-ons` -> `Sledovani.tv` -> `Basic` -> `Use inputstream.adaptive plugin`. I think it was turned off at first.

Of go to the `Adaptive inputsteam` plugin setting and try to tune its parameters.

I assume you did the system reboot after plugin installation :)

**Comment by johny-mnemonic** [comment]
@mirousek I am pretty sure, that without the plugin, I was unable to even pause it to go to toilet;-) So the plugin is big improvement in this regard, but it brings nothing more than pausing basically.
I restarted multiple times and upgraded from Kodi 18 to 19 since I installed the plugin.
Are there any settings for the plugin to try? I checked it and at fist glance, defaults look reasonable.
Maybe the important thing is, that I am running Kodi on Windows 10 HTPC.

**Comment by mirousek** [comment]
@johny-mnemonic Understood :)

I've tried the plugin on LibreELEC (Kodi 18.9 so far) on RPi3 only. Have no experience with Kodi on WIndows :(

Maybe @palinek has any hint?

**Comment by palinek** [comment]
> Maybe @palinek has any hint?

I also don't know about the possibility of re-wind/f-wind of live stream. But if you start the current show from EPG (play programme; not switch to channel), you're able to seek in the show from the beginning to current time.

**Comment by johny-mnemonic** [comment]
@palinek thanks for the hint, but I struggle to find anything resembling
"play programme" in the EPG.
I have only "switch to channel", "show details", "find similar", "add
schedule", "go to" and "artwork options".
And inside "show details", there is also only "switch to channel" option...

Dne po 22. 3. 2021 9:58 uživatel Palo Kisa ***@***.***>
napsal:

**Comment by palinek** [comment]
Don't you have any timeshift your purchased package?
I can see it:
![screenshot](https://user-images.githubusercontent.com/10990929/111974584-d5037800-8aff-11eb-8d70-456d24f02049.png)

**Comment by johny-mnemonic** [comment]
In case it depends on some extra paid package from Sledovanitv, than I most probably don't have it, which would probably explain missing buttons for "Record" and "Play Programme" on my side.

**Comment by palinek** [comment]
> extra paid package from Sledovanitv, than I most probably don't have it

AFIAK reasonable timeshift span is in all packages...https://sledovanitv.cz/services

**Comment by johny-mnemonic** [comment]
I have packages "Start", "HD" and "Smart TV", but I don't see any info about timeshift in any package description...
I am unable to play the show from the start neither in the web browser nor in the Android app, so I guess there is some limitation in the configuration of my account on sledovanitv.cz.

**Comment by mirousek** [comment]
Oh, absolutely forgot the packages selection + `Play Programme` button :) Sorry…

@palinek It seems he is in some partner network. Correct, @johny-mnemonic?

For example in `PilsFree` I have free package `Balíček Zpětné přehrávání až 7 dní + Nahrávky 50 hodin`, which is working for ČT & HBO groups. For Nova & Prima groups I had to buy `NP+` package in addition.

**Comment by johny-mnemonic** [comment]
Correct. I am in eurosignal.cz network and I have the sledovanitv.cz service as part of the optical internet connection.

**Comment by lukyrys** [comment]
@palinek hi thanks for hint, i have timeshift but i can play forward only programme few hour back (but not older)
now is 0:24 (this is not related to inputstream)
- http://502.cz/scr/kodi_2021-03-28_00-23-12.png this is ok, 2 programme back at ~23:30
- http://502.cz/scr/kodi_2021-03-28_00-22-53.png there missing "play programme", 4th programme back at ~22:15
in web player is all ok http://502.cz/scr/2021-03-28_00-27-09.png

next thing is with inputstream still can't rewind actual live stream only pause/play it without possibility skip stopped part there is video with trying clicking on progress bar or trying left/right arrow http://502.cz/scr/2021-03-28_00-42-04.mp4
