### ISSUE TITLE
Would it be easy to create an add-on for ModerniTv.cz?

### ISSUE THREAD

**Issue by hkobelka** [palinek/pvr.sledovanitv.cz#73]
##### New idea request
Hi,
at first thank you for this add-on. It works perfectly.
However i don't use sledovanitv.cz but i have modernitv.cz directly from my ISP.
Both web sites are from the same company and they also have an nearly identical design.
But the accounts are separated.

Would it be easy to create a separate Add-On for ModerniTv.cz ? Mabybe it is only a matter of some URLs.

Unfortunately i am not a C++Developer nor do i know something about Kodi Addon development.
So i can't be much of a help here. But i would gladly test any new changes for you.

Best regards
Hynek

**Comment by palinek** [comment]
Hi,
 if the interface is the same and just the server name differs, then from implementation perspective it is easy to clone this addon. But it would better approach to unify this one -> allowing it to talk to multiple backend types (one at a time of course).

**Comment by palinek** [comment]
Support for modernitv.cz is added in 60bf60f, released in [4.5.0-Matrix](https://github.com/palinek/pvr.sledovanitv.cz/releases/tag/4.5.0-Matrix)
