### ISSUE TITLE
EPG parsing incomplete?

### ISSUE THREAD

**Issue by Harvie** [palinek/pvr.sledovanitv.cz#74]
Hello,
i have this issue on regular basis. Do you have any idea what might be causing it?
Reboot / cache flush did not helped, after EPG was reloaded the problem appeared again.

##### Expected Behavior
All shows properly parsed:
![image](https://user-images.githubusercontent.com/276504/111207648-2c6a8b00-85ca-11eb-990d-664b72ddc354.png)

##### Current Behavior
Shows not being listed. Only one big time block is showed in EPG. Even when there is show before and after block parsed properly...
![image](https://user-images.githubusercontent.com/276504/111207544-0e9d2600-85ca-11eb-8e3f-52b348eecf77.png)

##### Possible Solution
Some shows are perhaps not properly parsed from sledovanitv api? Their website is aware of the show, but it does not go to the Kodi EPG. Maybe show "televizní noviny" often contains some illegal character in the description?

##### Steps to Reproduce (for bugs)
Every other day there is this problem on Nova

##### Context
Stara me kazdej tejden prudi, ze ji nejde pustit ulice. Pls help.

##### System Information

* pvr.sledovani.tv Version: 1.9.0 5390c53a006db160991792fbd11746d917f1309c
* Kodi Version: 18.7 Leia Git: 20200528 2c5354e70a
* OS Version:  Rasbian 32b (RPi4)

**Comment by palinek** [comment]
This seems rather random (I do not observe such behavior). Please, enable debug in settings and share the log (with sensitive data removed...) when it happens again.

**Comment by Harvie** [comment]
> This seems rather random

It seems to happen at least once a week, maybe more. Do you think there might be issue with sledovanitv API actualy not providing the data?

This was happening to me even with older (~year ago) version of plugin. Haven't yet upgraded Kodi from Leia to Matrix, do you think this might be affecting the issue?

I will surely try to capture some logs and let you know.

**Comment by Harvie** [comment]
Happens again right now. Here is the log.
[kodi.log-EPGBUG.txt](https://github.com/palinek/pvr.sledovanitv.cz/files/6305495/kodi.log-EPGBUG.txt)

**Comment by palinek** [comment]
Hm...in log there is are messages about information loaded:
```
...
2021-04-13 19:12:05.350 T:2485092560   DEBUG: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Loading TV show: nova - Ulice (4032), start=2021-04-13 18:30(epoch=1618331400)
2021-04-13 19:12:05.351 T:2485092560   DEBUG: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Loading TV show: nova - Televizní noviny, Sportovní noviny, Počasí, start=2021-04-13 19:30(epoch=1618335000)
2021-04-13 19:12:05.351 T:2485092560   DEBUG: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Loading TV show: nova - Anatomie života (Rodiče a děti), start=2021-04-13 20:20(epoch=1618338000)
...
```

I looked into the loading logic... it seems sane for me. For now I'm out of clue...

**Comment by Harvie** [comment]
But also there is this:

```
2021-04-13 19:12:22.948 T:2485092560   DEBUG: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Loading TV show: nova - 16:00 - 20:00, start=2021-04-20 16:00(epoch=1618927200
```

It says "2021-04-20", but maybe it somehow ends up in wrong day?

**Comment by palinek** [comment]
The start time is the unique identifier of EPG entry for channel.... so it definitely should be different -> 1618331400 vs. 1618927200

Btw. is it of any use to have such a long period of future EPG?

**Comment by Harvie** [comment]
> Btw. is it of any use to have such a long period of future EPG?

Probably not... I've been experimenting with different settings to solve this issue. Also i want to be able to play all recordings from the past available from sledovanitv servers. What settings do you reccomend use? Do you think it might affect this issue?

**Comment by Harvie** [comment]
Just checked and i had 14 days in past and 7 in future. Doesn't seem as crazy long period to me. But i lowered it to 3 days in future, just in case the week somehow "wraps around" showing items from next week instead of the current.

**Comment by palinek** [comment]
@Harvie is the issue still happening to you with the shortened future time slot?

**Comment by Harvie** [comment]
I think it is better now, but i don't really remember what i did. Is there possibility that having longer period displayed causes data corruption?

**Comment by palinek** [comment]
That's hard to say...there may have been a problem in the Kodi's EPG presentation.

**Comment by Harvie** [comment]
Hopefully i will be able to upgrade from kodi 18.x to 19.3 (as soon as they will include it in raspbian)
IIRC they were changing EPG related stuff, so it might be already fixed in kodi.
