### ISSUE TITLE
new provider to be added?

### ISSUE THREAD

**Issue by encheels** [palinek/pvr.sledovanitv.cz#75]
Hello,
##### Current Behavior

sledovanietv.sk provider is not present among the available service providers.
Would you please be so kind and take a look on?
Thanks

##### System Information

* pvr.sledovani.tv Version: 4.5.0
* Kodi Version: 19 [ Matrix ]
* OS Version: MacOS BigSur

**Comment by palinek** [comment]
Hi there is no need for sledovanietv.sk ... accounts from this provider are perfectly working with sledovanitv.cz.

**Comment by encheels** [comment]
OMG...sorry, bad creds saved from previous Kodi 18 deployment.

**Comment by mmiillaa11** [comment]
Ahoj.
Nešlo by udělat, aby šlo sk a cz současně máme obě linky zaplacené
Hi.
It would not be possible to do sk and cz at the same time we have both lines paid

**Comment by mmiillaa11** [comment]
Nechápu, ale děkuji.
