### ISSUE TITLE
Add of Nexus branch and related version

### ISSUE THREAD

**Issue by AlwinEsch** [palinek/pvr.sledovanitv.cz#78]
Since Kodi 20 Nexus has been available for a some months now, it is time to create an associated Nexus branch and release for all addons, for this then maybe "20.0.0-Nexus" for here (relates to you, on Kodi side, addon major equal to Kodi major).

I'm doing this at all addons where I have access, but you would have to make a change to this one.

**Comment by palinek** [comment]
Done -> https://github.com/palinek/pvr.sledovanitv.cz/branches

Please review, if anything else needed.

**Comment by palinek** [comment]
> release for all addons, for this then maybe "20.0.0-Nexus" 

Oh forgot about the releasing. Is this the new versioning style up from Nexus (the major version should match Kodi's major version)?

**Comment by AlwinEsch** [comment]
We use this for the addons in the team (https://github.com/kodi-pvr & https://github.com/xbmc), but it is not necessarily mandatory for outside. Here at the addon you are the boss :sunglasses:, only then is it easy to see what it belongs to :smiley:.

**Comment by AlwinEsch** [comment]
> Done -> https://github.com/palinek/pvr.sledovanitv.cz/branches
> 
> Please review, if anything else needed.

Yes, the most needed part change is missing on "Jenkinsfile" (https://github.com/palinek/pvr.sledovanitv.cz/blob/Nexus/Jenkinsfile), if there as Matrix becomes a release also deployed to Kodi 19 Matrix addons.

**Comment by palinek** [comment]
> We use this for the addons in the team

Done -> https://github.com/palinek/pvr.sledovanitv.cz/releases/tag/20.0.0-Nexus

**Comment by palinek** [comment]
> Yes, the most needed part change is missing on "Jenkinsfile" 

Is the Nexus ready? Can I just replace the `buildPlugin(version: "Matrix")` with `buildPlugin(version: "Nexus")`?

**Comment by AlwinEsch** [comment]
Yes, otherwise the release not comes to here https://mirrors.kodi.tv/addons/nexus/.

Also a bit bad as you now created release and addon will land here https://mirrors.kodi.tv/addons/matrix/pvr.sledovanitv.cz+windows-x86_64/ :cry:, will ask the team where has access to it and to delete there.

**Comment by palinek** [comment]
Sorry for that... :-S

Updated and pushed 20.0.1-Nexus tag.
