### ISSUE TITLE
Before the selected program is the end of the previous and after it the beginning of the next

### ISSUE THREAD

**Issue by ZdenekM** [palinek/pvr.sledovanitv.cz#83]
Sorry, this is rather a question... I am quite new to PVR on Kodi so I'm not sure whether it is normal that when I select some specific program from EPG, it plays approximately 5 minutes of the previous one, then the selected program, and afterward like 5 minutes of the next program. Can it be avoided or limited?

**Comment by palinek** [comment]
This is how the provider (sledovanitv) serves it. We can't do much with it on the addon side.

**Comment by ZdenekM** [comment]
Ok, thank you for your response. And what about skipping some (configurable?) amount of time in the beginning and stopping playback a little bit sooner? The intervals are probably constant so it might work maybe :)

**Comment by palinek** [comment]
We can't do that in the addon. We're just handing over the playback URL (got from sledovanitv server) to kodi backend.
