### ISSUE TITLE
Poradi kanalu

### ISSUE THREAD

**Issue by jendaHolarek** [palinek/pvr.sledovanitv.cz#86]
Ahoj, zacal jsem pouzivat tento doplnek v KODI, vse funguje, jen by me zajimalo jak:
1) nastavit poradi kanalu aby bylo jako mam nastavene na webu Sledovanitv
2) jak upravit poradi kanalu v oblibene skupine, napr. SPORT

Pouzivam verzi dolpnku 20.0.0

Dekuji

**Comment by palinek** [comment]
Hi.
 Channel ordering should follow the settings of web and re-ordering could be possible in Kodi's settings (Settings -> PVR & Live TV -> General -> (Use channel order from backend(s) / Use channel number from backend / Channel Manager / Group Manager)

**Comment by jendaHolarek** [comment]
Hi, I tried that but it doesn't work, the order is different than my setting on the website. Furthermore, in the preset group "Sport" there are also non-sports channels, e.g. Prima.
Thanks

**Comment by palinek** [comment]
>  I tried that but it doesn't work

Then this is something to report to kodi.

> Furthermore, in the preset group "Sport" there are also non-sports channels, e.g. Prima.

The group, into which the channel belongs is reported by sledovanitv backend. Nothing is done in that area by addon.

**Comment by jendaHolarek** [comment]
So now I know why it doesn't work.  I have two profiles (parents and me) and I adjusted the channel order in my profile, but the add-on probably pulls it from the first profile and that's why it didn't show up for me.  Wouldn't it be possible to add a profile option for channel order?
Thanks
