### ISSUE TITLE
Toggle audio stream

### ISSUE THREAD

**Issue by vencas** [palinek/pvr.sledovanitv.cz#87]
Audio stream in sledovanitv is unknown (czech) and you can't switch to alternate audio stream.
##### Expected Behavior

That you can switch from default (cz) to sk or en if available.
##### Current Behavior

There is only default unk audio stream

##### System Information

* pvr.sledovani.tv Version: 1.9.0.1
* Kodi Version: 18.9.0
* OS Version: CoreELEC 9.2.6

**Comment by palinek** [comment]
Audio streams are parts of the AV stream and as such are handled purely by Kodi. Addon just gives the URL of stream to Kodi backend.
Is something like audio switching possible with other clients? Maybe it is possible to get different URLs for streams from sledovanitv backend, but currently I'm not aware of parameters in the API, which could affect it.
