### ISSUE TITLE
Broken in current Kodi Matrix, works only in Kodi Nexus

### ISSUE THREAD

**Issue by cyberluke** [palinek/pvr.sledovanitv.cz#89]
Dobry den, I will switch to English:

I'm a new user and also tried to compile this component using cmake in Windows 10. Current Kodi is v19 Matrix. In repository there is version 20.0.0, this version have broken EPG and playing using EPG Guide.

This works in version 20.2.0, but for that you need Kodi Nexus Alpha 3 or similar (v20). This is not compatible with v19 due to dependency xml containing too much recent PVR Kodi module.

Would it be possible to have Jenkins build for current-gen Kodi?

Next-gen Kodi seems to not have 90% of skins and other plugins available yet.

Also I think your dependency jsonp is missing sha256 hash file in your repository:
```
-- ---- Configuring addon F:/github_kodi/xbmc/cmake/addons/xbmc/cmake/addons/addons/pvr.sledovanitv.cz/pvr.sledovanitv.cz.txt ----
-- Processing F:/github_kodi/pvr.sledovanitv.cz/depends/common/jsoncpp/jsoncpp.txt
-- jsoncpp url: http://mirrors.kodi.tv/build-deps/sources/jsoncpp-1.8.3.tar.gz
CMake Warning (dev) at F:/github_kodi/xbmc/cmake/scripts/common/HandleDepends.cmake:269 (message):
  F:/github_kodi/pvr.sledovanitv.cz/depends/common/jsoncpp/jsoncpp.sha256 is
  missing
Call Stack (most recent call first):
  CMakeLists.txt:455 (add_addon_depends)
```
This warning is for project developers.  Use -Wno-dev to suppress it.

I think it should be: 3671ba6051e0f30849942cc66d1798fdf0362d089343a83f704c09ee7156604f
for your file http://mirrors.kodi.tv/build-deps/sources/jsoncpp-1.8.3.tar.gz

**Comment by cyberluke** [comment]
I recommend updating project with these dependency metadata: https://github.com/kodi-pvr/pvr.hdhomerun/tree/Matrix/depends/common/jsoncpp

**Comment by cyberluke** [comment]
Ok, so I identified the issue is with v19 skin I have changed: TetradUI (https://github.com/gade01/skin.tetradui)

**Comment by palinek** [comment]
> Current Kodi is v19 Matrix. In repository there is version 20.0.0

Current version for Kodi Matrix is in branch `Matrix` and it is the 4.5.1-Matrix. For Nexus, the latest version is 20.3.0-Nexus

> Would it be possible to have Jenkins build for current-gen Kodi?

https://jenkins.kodi.tv/view/Addons/job/palinek/job/pvr.sledovanitv.cz/job/Matrix/

> Also I think your dependency jsonp is missing sha256 hash file in your repository:

> I recommend updating project with these dependency metadata: https://github.com/kodi-pvr/pvr.hdhomerun/tree/Matrix/depends/common/jsoncpp

Please, PR with such change will be welcome.

**Comment by cyberluke** [comment]
I'm new here, I don't have too much Kodi experience yet.

As I found out it is a skin issue I created issue here: https://github.com/gade01/skin.tetradui/issues/14
