### ISSUE TITLE
Video stream takes long to start (Xbox One S)

### ISSUE THREAD

**Issue by robertblazek** [palinek/pvr.sledovanitv.cz#9]
The audio stream starts near-instantly, video starts about 10 seconds later, both are in perfect sync.

**Comment by palinek** [comment]
What version are you using? Do you use inpustream.adaptive?... 

pvr.sledovanitv.cz doesn't do anything with the stream, it just gives the stream URL to kodi (which plays it with the default decoder or with inputstream.adaptive). So we can't do much with this. You need to go deeper and raise the issue to kodi core devs or inputstream.adaptive devs.
