### ISSUE TITLE
Add-on is missing in Kodi 20 Nexus on Android

### ISSUE THREAD

**Issue by TomKyblik** [palinek/pvr.sledovanitv.cz#91]
Well the title sums it up -- just got the Kodi updated to version 20 Nexus on Google Chromecast with TV and add-on is not available anymore in official Kodi repository

**Comment by palinek** [comment]
@ksooo @AlwinEsch @Rechi Could you, guys, help here? I'm just seeing, that the builds in jenkins are failing -> https://jenkins.kodi.tv/view/Addons/job/palinek/view/default/job/pvr.sledovanitv.cz/job/Nexus/79/console.
But I don't know, how to fix it of if even I can fix this by myself.

**Comment by Rechi** [comment]
please install https://github.com/apps/jenkins-xbmc and grant access to this repository

**Comment by palinek** [comment]
Thanks @Rechi, I've installed and granted the asked permissions. Then after tirggering new build in jenkins, I see the same error.
Am I doing something wrong?

**Comment by Rechi** [comment]
You just have been too quick. I had to do Jenkins configuration changes. It's working now.

**Comment by palinek** [comment]
Thanks a lot, @Rechi.
