### ISSUE TITLE
Nefunguje DOplnok / nôt work . 

### ISSUE THREAD

**Issue by nano143** [palinek/pvr.sledovanitv.cz#93]
Doplnok už 4 deň Nefunguje nôt work. 
pri odinstalci 1x načíta a potom už nie . Je tam chyba . Od kedy je vydaný nexus stále sú s ním problémy . Kľudne aj zaplatím za odstránenie chyby . Dakujem 

lebo trvá to až príliš dlho a nedá sa to žiadno vyriešiť že to nikomu nejde .

**Comment by palinek** [comment]
Dup. of #92
