### ISSUE TITLE
Nôt work please fix 

### ISSUE THREAD

**Issue by nano143** [palinek/pvr.sledovanitv.cz#94]
hello palinka. the plugin has not been working for 4 days. when it is uninstalled and installed, it loads Kabali, then not anymore. it says only loss of connection. I have many friends who stopped working for them and currently the add-on does not work for anyone.

how to solve this error? I will gladly pay for it.

**Comment by palinek** [comment]
Dup. of #92

**Comment by palinek** [comment]
Please, continue in #92. Especially attaching the logs can help to analyze the situation, as I'm not experiencing such behavior.
