### ISSUE TITLE
Instalace doplňku sledovanitv 

### ISSUE THREAD

**Issue by 528571** [palinek/pvr.sledovanitv.cz#98]
Zkouším to přidat do KODI jako zip file a stále mi to píše že zip má neplatný formát. Zip soubor mám stažen na USB.
Co dělám špatně....jedu dle tohoto návodu: (https://www.firesticktricks.com/install-kodi-addon.html) Zkoušel jsem i kopírovat ZIP z flashky do root/tmp a nejde to .....
Může mi někdo poradit, jsem začátečník....
Dík za odpověď.
Pavel

**Comment by nano143** [comment]
Ahoj nainštaluj si to priamo z kodi repozitaru. Pvr klienti , no nejako ti to nepomôže . Doplnok zasa nefunguje
